"""Disable critical risk/time/reserved guards in restored isolated source copies."""

from check_execution_guards import MUTATIONS as EXECUTION_MUTATIONS
from check_execution_guards import main

EXECUTION_MUTATIONS[:] = [
    ("risk_unconfigured", "risk/engine.py",
     'if not self.configuration.configured or p is None or a is None or i is None:',
     'if False:', "tests/test_risk_decisions.py::test_unconfigured_never_approves"),
    ("risk_account_age", "risk/engine.py",
     'if not 0 <= age <= p.max_account_age_seconds or not account["verified"]:',
     'if False:', "tests/test_risk_decisions.py::test_stale_account_and_warmup_block"),
    ("risk_warmup", "risk/engine.py",
     'self.state.warm_snapshots >= p.warmup_snapshots',
     'True', "tests/test_risk_decisions.py::test_stale_account_and_warmup_block"),
    ("risk_future_forecast", "risk/engine.py",
     'or h.forecast_available_utc > now or h.forecast_expiry_utc <= now',
     'or False or h.forecast_expiry_utc <= now',
     'tests/test_risk_decisions.py::test_health_rejects_explicitly'),
    ("risk_alpha_identity", "risk/engine.py",
     'or h.model_id != contract["model"] or h.feature_id != contract["features"]',
     'or False or False', 'tests/test_risk_decisions.py::test_health_rejects_explicitly'),
    ("risk_min_quantity", "risk/engine.py", 'if quantity < i.min_lots:', 'if False:',
     'tests/test_risk_decisions.py::test_minimum_exceeds_budget_never_round_up'),
    ("risk_pending", "risk/engine.py", 'if self.state.reservations:', 'if False:',
     'tests/test_risk_state.py::test_opposing_pending_is_not_netting_credit'),
    ("risk_drawdown", "risk/engine.py", 'if self.state.drawdown >= p.drawdown_limit:', 'if False:',
     'tests/test_risk_state.py::test_loss_costs_external_flows_daily_reset_and_hwm_persist'),
    ("risk_checkpoint", "risk/engine.py",
     'or checkpoint.get("configuration_sha256") != configuration.identity', 'or False',
     'tests/test_risk_state.py::test_restart_never_ready_and_incompatible_or_corrupt_state_refused'),
    ("risk_execution_capability", "execution/engine.py",
     'if self._risk_authority is not None and (', 'if False and (',
     'tests/test_risk_portfolio.py::test_raw_call_cannot_reuse_current_authorized_context'),
    ("risk_submit_boundary", "execution/engine.py",
     'if self._risk_boundary is not None and not self._risk_boundary(', 'if False and not self._risk_boundary(',
     'tests/test_risk_portfolio.py::test_submission_guard_works_without_secondary_portfolio_checks'),
    ("risk_fill_notional", "risk/portfolio.py", 'if required_margin > r.margin + 1e-9:', 'if False:',
     'tests/test_risk_portfolio.py::test_quote_gap_and_bad_health_prevent_pending_fill'),
    ("risk_rearm", "risk/engine.py",
     'or self.state.daily_loss >= p.daily_loss_limit or self.state.drawdown >= p.drawdown_limit',
     'or False or False', 'tests/test_risk_state.py::test_loss_costs_external_flows_daily_reset_and_hwm_persist'),
    ("reserved_period", "execution/io.py", 'if local_time(b, config) > datetime(2022, 1, 1):',
     'if False and local_time(b, config) > datetime(2022, 1, 1):',
     'tests/test_execution_readiness.py::test_utc_is_explicit_and_stage12_cannot_open_a_new_reserved_path'),
    ("strict_fill_time", "execution/engine.py", 'o.arrival_utc < stamp < o.expires_utc',
     'o.arrival_utc <= stamp < o.expires_utc',
     'tests/test_execution_engine.py::test_latency_never_fills_an_earlier_or_same_arrival_quote'),
    ("risk_fold_eligibility", "risk/portfolio.py",
     'if any(not a.eligible_at(cutoff) for a in alphas) or len({a.alpha_id for a in alphas}) != len(alphas):',
     'if False:', 'tests/test_risk_portfolio.py::test_governed_scientific_entry_refuses_future_or_failed_eligibility'),
    ("risk_external_flow", "risk/engine.py",
     'adjusted = snapshot.equity - snapshot.external_flow_total', 'adjusted = snapshot.equity',
     'tests/test_risk_state.py::test_loss_costs_external_flows_daily_reset_and_hwm_persist'),
    ("risk_quantity_rounding", "risk/engine.py", 'quantity = math.floor(', 'quantity = math.ceil(',
     'tests/test_risk_decisions.py::test_known_horizon_loss_rounding_and_caps'),
    ("risk_margin_entry_costs", "risk/engine.py",
     'margin_per_lot = market.ask * conversion * i.margin_notional_fraction + entry_cash_loss_per_lot',
     'margin_per_lot = market.ask * conversion * i.margin_notional_fraction',
     'tests/test_risk_decisions.py::test_margin_cap_reserves_immediate_costs_and_quote_side_mark'),
]

if __name__ == "__main__":
    raise SystemExit(main())
